### ISSUE TITLE
shapefile.proj should be text not array buffer

### ISSUE THREAD

**Issue by SchroeC** [kobesin/GeoConvert#1]
var shapefile = {};
shapefile.shp = arrayBuffer_shp;
shapefile.dbf = arrayBuffer_dbf;

//optional
//shapefile.prj = arrayBuffer_prj; didnt work
shapefile.prj = string_prj; //worked for me

**Comment by kobesin** [comment]
Hi, thanks for your comment.
Yes, shapefile.prj should be string.
I will correct README.md.
