### ISSUE TITLE
for use on leaflet webmap

### ISSUE THREAD

**Issue by aliencraft1512** [kobesin/GeoConvert#4]
newbie alert here.Is it possible to use the conversion on a leaflet map?

**Comment by kobesin** [comment]
Yes, you can convert files in supported formats to geojson. Then use Leaflet L.geoJSON to add geojson on the map as shown below.
[https://leafletjs.com/reference-1.6.0.html#geojson](https://leafletjs.com/reference-1.6.0.html#geojson)

**Comment by aliencraft1512** [comment]
Great!but i guess the same does not happen with the KMZ conversion(with embedded images)?

**Comment by kobesin** [comment]
So far KMZ conversion does not support embedded images. The library was originally designed to support simple style conversions. I think the design supports more complex styles, depending on the library used later.
